CREATE TABLE slots (
    attestationscount BIGINT NOT NULL,
    attesterslashingscount BIGINT NOT NULL,
    blockroot CHAR(66) NOT NULL,
    depositscount BIGINT NOT NULL,
    epoch BIGINT NOT NULL,
    eth1data_blockhash CHAR(66),
    eth1data_depositcount BIGINT NOT NULL,
    eth1data_depositroot CHAR(66),
    exec_base_fee_per_gas BIGINT NOT NULL,
    exec_block_hash CHAR(66),
    exec_block_number BIGINT NOT NULL,
    exec_extra_data TEXT ,
    exec_fee_recipient CHAR(42),
    exec_gas_limit BIGINT NOT NULL,
    exec_gas_used BIGINT NOT NULL,
    exec_logs_bloom TEXT,
    exec_parent_hash CHAR(66),
    exec_random CHAR(66),
    exec_receipts_root CHAR(66),
    exec_state_root CHAR(66),
    exec_timestamp BIGINT NOT NULL,
    exec_transactions_count BIGINT NOT NULL,
    graffiti CHAR(66),
    graffiti_text TEXT,
    parentroot CHAR(66),
    proposer BIGINT NOT NULL,
    proposerslashingscount BIGINT NOT NULL,
    randaoreveal CHAR(194),
    signature CHAR(194),
    slot BIGINT PRIMARY KEY,
    stateroot CHAR(66),
    status CHAR(1),
    syncaggregate_bits CHAR(130),
    syncaggregate_participation FLOAT,
    syncaggregate_signature TEXT,
    voluntaryexitscount BIGINT NOT NULL,
    withdrawalcount BIGINT NOT NULL
);